In [2]:
import torch

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [9]:
x_one = torch.ones_like(x_data)
print(f"Ones Tensor:\n{x_data}\n")
x_rand = torch.rand_like(x_data,dtype = torch.float)
print(f"Rnes Tensor:\n{x_rand}\n")

Ones Tensor:
tensor([[1, 2],
        [3, 4]])

Rnes Tensor:
tensor([[0.3437, 0.4323],
        [0.2866, 0.0993]])



In [15]:
from PIL import Image
from torchvision import transforms
image_path = r'webwxgetmsgimg.jpg'
image = Image.open(image_path)
transform = transforms.ToTensor()
tensor_image = transform(image)
print(type(tensor_image))
print(tensor_image)

<class 'torch.Tensor'>
tensor([[[0.0157, 0.0157, 0.0196,  ..., 0.0275, 0.0157, 0.0157],
         [0.0157, 0.0157, 0.0196,  ..., 0.0196, 0.0275, 0.0275],
         [0.0157, 0.0157, 0.0196,  ..., 0.0157, 0.0235, 0.0235],
         ...,
         [0.0314, 0.0314, 0.0235,  ..., 0.0157, 0.0039, 0.0039],
         [0.0314, 0.0314, 0.0235,  ..., 0.0078, 0.0039, 0.0039],
         [0.0314, 0.0314, 0.0235,  ..., 0.0000, 0.0039, 0.0039]],

        [[0.0235, 0.0235, 0.0196,  ..., 0.0314, 0.0196, 0.0196],
         [0.0235, 0.0235, 0.0196,  ..., 0.0235, 0.0314, 0.0314],
         [0.0235, 0.0235, 0.0196,  ..., 0.0196, 0.0275, 0.0275],
         ...,
         [0.0275, 0.0275, 0.0196,  ..., 0.0235, 0.0118, 0.0118],
         [0.0275, 0.0275, 0.0196,  ..., 0.0157, 0.0118, 0.0118],
         [0.0275, 0.0275, 0.0196,  ..., 0.0078, 0.0118, 0.0118]],

        [[0.0118, 0.0118, 0.0118,  ..., 0.0118, 0.0000, 0.0000],
         [0.0118, 0.0118, 0.0118,  ..., 0.0039, 0.0118, 0.0118],
         [0.0118, 0.0118, 0.0118,  

In [21]:
to_PIL = transforms.ToPILImage()
image_s = to_PIL(tensor_image)
print(type(image_s))
image_s.save('转换后的图片.jpg')

<class 'PIL.Image.Image'>
